### ISSUE TITLE
Need to fill demo data: the list is empty:null

### ISSUE THREAD

**Issue by devedroy** [devedroy/My-Doc#27]
```java
FATAL EXCEPTION: main
                                                                                                    Process: com.devedroy.mydoc, PID: 2489
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                                                    	at com.devedroy.mydoc.views.homepage.RecyclerDemoAdapter.getItemCount(RecyclerDemoAdapter.java:42)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4214)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3680)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1351)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.widget.ScrollView.onMeasure(ScrollView.java:368)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
                                                                                                    	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
                                                                                                    	at android.view.View.measure(View.java:23454)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:812)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:907)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                    	at android.os.Looper.loop(Looper.java:216)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7625)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by devedroy** [comment]
Fixed.
